name: WakaTime
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
